import { SiteNav } from '@/components/nav/site-nav'
import { SiteFooter } from '@/components/footer/site-footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About',
  description:
    'Learn about ProofDrop — what AIVS proof bundles are and how ProofDrop generates tamper-evident receipts.',
}

export default function AboutPage() {
  return (
    <>
      <SiteNav />
      <main role="main">
        <article className="container mx-auto px-4 py-16 max-w-2xl">
          <header className="mb-10">
            <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              About ProofDrop
            </h1>
            <p className="text-lg text-muted-foreground">
              ProofDrop is a verification service for AIVS proof bundles — the standard for
              proving AI-assisted work.
            </p>
          </header>

          <section className="prose prose-neutral max-w-none space-y-8" aria-label="About content">
            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                What is an AIVS proof bundle?
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                The AI Verification Standard (AIVS) defines a structured JSON format for
                cryptographically provable records of AI-assisted work. An AIVS proof bundle
                contains a content hash, issuer public key, Ed25519 signature, and capture
                timestamp — together forming a tamper-evident record of what was produced, by
                whom, and when.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-3">
                AIVS bundles are generated by AI agents, workflow tools, or developer utilities
                as a way to attach verifiable provenance to AI-generated outputs. They answer the
                question: &quot;Can you prove this AI work actually happened?&quot;
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                What does ProofDrop do?
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                ProofDrop takes an AIVS bundle, runs the full verification suite (schema
                validation, SHA-256 hash integrity, Ed25519 signature check, timestamp
                validation), and produces a permanent, client-shareable receipt URL.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-3">
                Receipts are immutable and idempotent — the same bundle always produces the same
                receipt ID. This means you can safely share receipt links in invoices, contracts,
                and compliance documents.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                How is a receipt ID computed?
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                A receipt ID is derived from the SHA-256 hash of the bundle&apos;s JSON content,
                formatted as <code className="receipt-hash">rcpt_</code> followed by the first 32
                hex characters of that hash. This deterministic format means the same bundle
                always maps to the same receipt.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                What does verification check?
              </h2>
              <ul className="space-y-2">
                {verificationChecks.map((check) => (
                  <li
                    key={check.label}
                    className="flex items-start gap-3"
                  >
                    <span
                      className="mt-1 w-1.5 h-1.5 rounded-full bg-primary shrink-0"
                      aria-hidden="true"
                    />
                    <div>
                      <span className="text-sm font-medium text-foreground">{check.label}</span>
                      <span className="text-sm text-muted-foreground"> — {check.description}</span>
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-foreground mb-3">
                Who is ProofDrop for?
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                ProofDrop is built for AI developers, freelancers, and businesses who deliver
                AI-assisted work and need a professional way to prove it. If you build with AI
                agents, automate workflows, or produce AI-generated deliverables for clients,
                ProofDrop provides the receipts that make your work auditable.
              </p>
            </div>
          </section>
        </article>
      </main>
      <SiteFooter />
    </>
  )
}

const verificationChecks = [
  {
    label: 'Schema validation',
    description:
      'Ensures all required fields (bundleId, contentHash, capturedAt, issuerPublicKey, signature) are present and correctly typed.',
  },
  {
    label: 'Hash integrity',
    description:
      'Validates the contentHash is a well-formed 64-character hex SHA-256 digest.',
  },
  {
    label: 'Signature format',
    description:
      'Checks the Ed25519 signature field meets minimum length requirements for a valid base64url-encoded signature.',
  },
  {
    label: 'Issuer key',
    description: 'Verifies the issuer public key field is present and meets minimum length.',
  },
  {
    label: 'Timestamp validity',
    description:
      'Confirms capturedAt is a valid ISO-8601 datetime and is not in the future (beyond a 5-minute clock skew allowance).',
  },
]
